server:
  port: 8090

spring:
  datasource:
    #    url: jdbc:mysql://172.16.9.106:3306/ytwl_xcx_back
    url: jdbc:mysql://172.16.9.106:3306/ytwl_second_test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 禁用 Spring Security 自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  web:
    resources:
      static-locations:
        - file:./resources/static/
        - file:./resources/dist/

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


upload:
  directory: resources/static/uploads



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jwt:
  tokenPrefix: Bearer
  secret: utek123456
  expireTime: 24

mybatis:
  mapper-locations: classpath:mapper/*xml

div_key:
  CLOUD_BACKEND: "172.31.1.200:8000"
  Gb28181Ws: "ws://172.16.9.93"
  Gb28181Url: "http://172.16.9.93:5800"






























